using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using ArxisStudio.Markup.Json;
using ArxisStudio.Markup.Json.Generator.Models;
using ArxisStudio.Markup.Json.Generator.Services;
using ArxisStudio.Markup.Json.Generator.Utility;
using Microsoft.CodeAnalysis;

namespace ArxisStudio.Markup.Json.Generator.Builders
{
    internal class ComponentSourceBuilder
    {
        private readonly TypeResolver _resolver;
        private readonly ValueFormatter _formatter;
        private readonly SourceProductionContext _context;

        internal ComponentSourceBuilder(TypeResolver resolver, SourceProductionContext context)
        {
            _resolver = resolver;
            _formatter = new ValueFormatter(resolver);
            _context = context;
        }

        internal string Build(UiDocument document, ClassInfo classInfo, string assemblyName, string fileName)
        {
            using var stringWriter = new StringWriter();
            using var writer = new IndentedTextWriter(stringWriter, "    ");

            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using global::Avalonia.Controls;");
            writer.WriteLine("using global::Avalonia.Markup.Xaml;");
            writer.WriteLine("using global::Avalonia.Data;");
            writer.WriteLine();
            
            writer.WriteLine($"namespace {classInfo.Namespace}");
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine($"public partial class {classInfo.ClassName}");
            writer.WriteLine("{");
            writer.Indent++;

            var controls = CollectFields(document, classInfo.BaseClass);
            foreach (var control in controls.DistinctBy(c => c.Name))
            {
                writer.WriteLine($"internal global::{control.Type} {control.Name};");
            }
            writer.WriteLine();

            writer.WriteLine("public void InitializeComponent()");
            writer.WriteLine("{");
            writer.Indent++;

            BuildMethodBody(writer, document, classInfo.BaseClass ?? "Avalonia.Controls.UserControl", assemblyName, fileName);

            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");
            writer.Indent--;
            writer.WriteLine("}");

            return stringWriter.ToString();
        }

        private void BuildMethodBody(IndentedTextWriter writer, UiDocument document, string baseClassName, string assemblyName, string fileName)
        {
            var propertyGenerator = new PropertyGenerator(_resolver, _formatter, _context, assemblyName, fileName);
            
            var parentType = _resolver.ResolveType(baseClassName) 
                             ?? _resolver.ResolveType($"Avalonia.Controls.{baseClassName}");

            if (parentType == null)
            {
                 // Warning: базовый класс не найден
                 return; 
            }

            propertyGenerator.GenerateHostResources(writer, "this", document.Root.Resources);
            propertyGenerator.GenerateHostStyles(writer, "this", document.Root.Styles);

            foreach (var prop in document.Root.Properties)
            {
                propertyGenerator.GeneratePropertyAssignment(
                    writer, "this", parentType, prop.Key, prop.Value);
            }
        }
        
        private List<ControlInfo> CollectFields(UiDocument document, string? baseClassName)
        {
             var controls = new List<ControlInfo>();
             var parentType = baseClassName != null ? _resolver.ResolveType(baseClassName) : null;
             CollectFieldsFromProperties(document.Root.Properties, parentType, controls);
             return controls;
        }

        private void CollectFieldsFromProperties(IReadOnlyDictionary<string, UiValue> properties, INamedTypeSymbol? parentType, List<ControlInfo> controls)
        {
            foreach (var propEntry in properties)
            {
                if (propEntry.Value is NodeValue nodeValue)
                {
                    string? name = FindControlName(nodeValue.Node);
                    if (name != null) controls.Add(new ControlInfo(nodeValue.Node.TypeName, name));
                    var childType = _resolver.ResolveType(nodeValue.Node.TypeName);
                    CollectFieldsFromProperties(nodeValue.Node.Properties, childType, controls);
                    CollectFieldsFromStyles(nodeValue.Node.Styles, controls);
                    CollectFieldsFromResources(nodeValue.Node.Resources, controls);
                }
                else if (propEntry.Value is CollectionValue collectionValue)
                {
                    foreach (var item in collectionValue.Items)
                    {
                        if (item is NodeValue childNode)
                        {
                             string? name = FindControlName(childNode.Node);
                             if (name != null) controls.Add(new ControlInfo(childNode.Node.TypeName, name));
                             var childType = _resolver.ResolveType(childNode.Node.TypeName);
                             CollectFieldsFromProperties(childNode.Node.Properties, childType, controls);
                             CollectFieldsFromStyles(childNode.Node.Styles, controls);
                             CollectFieldsFromResources(childNode.Node.Resources, controls);
                        }
                    }
                }
            }
        }

        private void CollectFieldsFromStyles(UiStyles? styles, List<ControlInfo> controls)
        {
            if (styles == null)
            {
                return;
            }

            foreach (var item in styles.Items)
            {
                if (item is not StyleNodeValue styleNode)
                {
                    continue;
                }

                string? name = FindControlName(styleNode.Node);
                if (name != null)
                {
                    controls.Add(new ControlInfo(styleNode.Node.TypeName, name));
                }

                var styleType = _resolver.ResolveType(styleNode.Node.TypeName);
                CollectFieldsFromProperties(styleNode.Node.Properties, styleType, controls);
                CollectFieldsFromStyles(styleNode.Node.Styles, controls);
                CollectFieldsFromResources(styleNode.Node.Resources, controls);
            }
        }

        private void CollectFieldsFromResources(UiResources? resources, List<ControlInfo> controls)
        {
            if (resources == null)
            {
                return;
            }

            foreach (var entry in resources.Values.Values)
            {
                if (entry is not NodeValue nodeValue)
                {
                    continue;
                }

                string? name = FindControlName(nodeValue.Node);
                if (name != null)
                {
                    controls.Add(new ControlInfo(nodeValue.Node.TypeName, name));
                }

                var resourceType = _resolver.ResolveType(nodeValue.Node.TypeName);
                CollectFieldsFromProperties(nodeValue.Node.Properties, resourceType, controls);
                CollectFieldsFromStyles(nodeValue.Node.Styles, controls);
                CollectFieldsFromResources(nodeValue.Node.Resources, controls);
            }
        }

        private static string? FindControlName(UiNode node)
        {
            if (node.Properties.TryGetValue("Name", out var value) &&
                value is ScalarValue { Value: string s })
            {
                return s;
            }

            return null;
        }
    }
}
