using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using AvaloniaDesigner.Generator.Models;
using AvaloniaDesigner.Generator.Services;
using AvaloniaDesigner.Generator.Utility;
using Microsoft.CodeAnalysis;

namespace AvaloniaDesigner.Generator.Builders
{
    public class FormClassBuilder
    {
        private readonly TypeResolver _resolver;
        private readonly ValueFormatter _formatter;
        private readonly SourceProductionContext _context;

        public FormClassBuilder(TypeResolver resolver, SourceProductionContext context)
        {
            _resolver = resolver;
            _formatter = new ValueFormatter(resolver);
            _context = context;
        }

        public string Build(AvaloniaModel model, string rootNamespace)
        {
            using var stringWriter = new StringWriter();
            using var writer = new IndentedTextWriter(stringWriter, "    ");

            string ns = $"{rootNamespace}.{model.NamespaceSuffix}";

            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("using global::Avalonia.Controls;");
            writer.WriteLine("using global::Avalonia.Markup.Xaml;");
            writer.WriteLine("using global::Avalonia.Data;");
            writer.WriteLine();
            
            writer.WriteLine($"namespace {ns}");
            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine($"public partial class {model.FormName} : global::{model.ParentClassType}");
            writer.WriteLine("{");
            writer.Indent++;

            var controls = CollectFields(model);
            foreach (var control in controls.DistinctBy(c => c.Name))
            {
                writer.WriteLine($"internal global::{control.Type} {control.Name};");
            }
            writer.WriteLine();

            writer.WriteLine("public void InitializeComponent()");
            writer.WriteLine("{");
            writer.Indent++;

            BuildMethodBody(writer, model);

            writer.Indent--;
            writer.WriteLine("}");
            
            writer.Indent--;
            writer.WriteLine("}");
            
            writer.Indent--;
            writer.WriteLine("}");

            return stringWriter.ToString();
        }

        private void BuildMethodBody(IndentedTextWriter writer, AvaloniaModel model)
        {
            var propertyGenerator = new PropertyGenerator(_resolver, _formatter, _context);
            var parentType = _resolver.ResolveType(model.ParentClassType);

            foreach (var prop in model.Properties)
            {
                propertyGenerator.GeneratePropertyAssignment(
                    writer, "this", parentType, prop.Key, prop.Value);
            }
        }
        
        private List<ControlInfo> CollectFields(AvaloniaModel model)
        {
             var controls = new List<ControlInfo>();
             var parentType = _resolver.ResolveType(model.ParentClassType);
             CollectFieldsFromProperties(model.Properties, parentType, controls);
             return controls;
        }

        private void CollectFieldsFromProperties(Dictionary<string, PropertyModel> properties, INamedTypeSymbol? parentType, List<ControlInfo> controls)
        {
            foreach (var propEntry in properties)
            {
                var prop = propEntry.Value;
                if (!string.IsNullOrEmpty(prop.Type))
                {
                    string? name = FindControlName(prop);
                    if (name != null) controls.Add(new ControlInfo(prop.Type, name));
                    
                    var childType = _resolver.ResolveType(prop.Type);
                    CollectFieldsFromProperties(prop.Properties, childType, controls);
                }
                else if (prop.Items != null)
                {
                    foreach (var item in prop.Items)
                    {
                        if (!string.IsNullOrEmpty(item.Type))
                        {
                             string? name = FindControlName(item);
                             if (name != null) controls.Add(new ControlInfo(item.Type, name));
                             var childType = _resolver.ResolveType(item.Type);
                             CollectFieldsFromProperties(item.Properties, childType, controls);
                        }
                    }
                }
            }
        }

        private string? FindControlName(PropertyModel model)
        {
            if (model.Properties.TryGetValue("Name", out var p) && p.Value is string s) return s;
            return null;
        }
    }
}