using System.Text;
using AvaloniaDesigner.Generator.Models;
using AvaloniaDesigner.Generator.Services;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Text.Json;
using AvaloniaDesigner.Generator.Utility;

namespace AvaloniaDesigner.Generator.Builders
{
    public class FormClassBuilder
    {
        private readonly TypeResolver _resolver;
        private readonly ValueFormatter _formatter;
        private readonly SourceProductionContext _context;

        public FormClassBuilder(TypeResolver resolver, SourceProductionContext context)
        {
            _resolver = resolver;
            _context = context;
            _formatter = new ValueFormatter(resolver);
        }

        public string Build(AvaloniaModel model, string rootNamespace)
        {
            // ... (методы Build, BuildMethodBody без изменений, кроме того, что они теперь используют обновленный CollectFields) ...
            var sb = new StringBuilder();
            string ns = $"{rootNamespace}.{model.NamespaceSuffix}";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using global::Avalonia.Controls;"); // Часто нужно для Children
            sb.AppendLine("using global::System.Collections.Generic;");
            sb.AppendLine("using global::Avalonia.Media;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {model.FormName} : global::{model.ParentClassType}");
            sb.AppendLine("    {");

            // --- 1. Сбор всех полей ---
            var namedControls = CollectFields(model);

            // --- 2. Генерация полей ---
            foreach (var control in namedControls.DistinctBy(c => c.Name))
            {
                sb.AppendLine($"        internal global::{control.Type} {control.Name};");
            }

            sb.AppendLine();
            sb.AppendLine("        public void InitializeComponent()");
            sb.AppendLine("        {");

            BuildMethodBody(sb, model);

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void BuildMethodBody(StringBuilder sb, AvaloniaModel model)
        {
            var propertyGenerator = new PropertyGenerator(_resolver, _formatter, _context);
            var parentType = _resolver.ResolveType(model.ParentClassType);

            foreach (var prop in model.Properties)
            {
                // Для свойств верхнего уровня мы не можем передать Name через модель,
                // потому что model.Properties - это свойства ParentClassType (например, Width, Content).
                // Мы будем полагаться на PropertyGenerator, который сам ищет Name в дочерних свойствах.
                
                propertyGenerator.GeneratePropertyAssignment(
                    sb, "this", parentType, prop.Key, prop.Value);
            }
        }
        
        // --- ИСПРАВЛЕННЫЙ МЕТОД СБОРА ПОЛЕЙ ---
        private List<ControlInfo> CollectFields(AvaloniaModel model)
        {
            var controls = new List<ControlInfo>();
            // Получаем тип класса, чтобы начать рекурсию с его свойств
            var parentType = _resolver.ResolveType(model.ParentClassType);
            CollectFieldsFromProperties(model.Properties, parentType, controls);
            return controls;
        }
        
        // *** НОВЫЙ МЕТОД: ДОБАВЛЕН ТИП РОДИТЕЛЯ (parentType) ДЛЯ АНАЛИЗА КОЛЛЕКЦИЙ ***
        private void CollectFieldsFromProperties(
            Dictionary<string, PropertyModel> properties, 
            INamedTypeSymbol? parentType, // Тип родительского объекта, содержащего эти свойства
            List<ControlInfo> controls)
        {
            foreach (var propEntry in properties)
            {
                var prop = propEntry.Value;
                var propertyName = propEntry.Key;
                
                IPropertySymbol? targetPropSymbol = parentType != null 
                    ? _resolver.FindProperty(parentType, propertyName) 
                    : null;

                // --- 1. Обработка обычного свойства, содержащего контрол (Content, Child, Template) ---
                if (!string.IsNullOrEmpty(prop.Type))
                {
                    string? controlName = FindControlName(prop);

                    if (!string.IsNullOrEmpty(controlName))
                    {
                        controls.Add(new ControlInfo 
                        { 
                            Type = prop.Type, 
                            Name = controlName 
                        });
                    }
                    
                    // Рекурсивный вызов для вложенных свойств
                    var childType = _resolver.ResolveType(prop.Type);
                    CollectFieldsFromProperties(prop.Properties, childType, controls);
                }
                
                // --- 2. Обработка свойства-коллекции (Children, Items) ---
                else if (targetPropSymbol != null && _resolver.IsCollectionType(targetPropSymbol.Type))
                {
                    // Проходим по элементам коллекции (ключам "0", "1", "2"...)
                    foreach (var collectionElementEntry in prop.Properties)
                    {
                        var elementModel = collectionElementEntry.Value;
                        
                        // Если элемент коллекции — это контрол (у него есть Type)
                        if (!string.IsNullOrEmpty(elementModel.Type))
                        {
                            string? controlName = FindControlName(elementModel);

                            if (!string.IsNullOrEmpty(controlName))
                            {
                                controls.Add(new ControlInfo 
                                { 
                                    Type = elementModel.Type, 
                                    Name = controlName 
                                });
                            }
                            
                            // Рекурсивный вызов для свойств этого элемента (чтобы найти вложенные именованные контролы)
                            var elementType = _resolver.ResolveType(elementModel.Type);
                            CollectFieldsFromProperties(elementModel.Properties, elementType, controls);
                        }
                    }
                }
                // Примитивные свойства (Value.HasValue) игнорируются здесь
            }
        }
        
        private string? FindControlName(PropertyModel model)
        {
            if (model.Properties.TryGetValue("Name", out PropertyModel? nameProp) && nameProp.Value.HasValue)
            {
                if (nameProp.Value.Value.ValueKind == JsonValueKind.String)
                {
                    return nameProp.Value.Value.GetString();
                }
            }
            return null;
        }
    }
}