using System.Collections.Generic;
using System.Linq;
using System.Text;
using AvaloniaDesigner.Generator.Models;
using AvaloniaDesigner.Generator.Services;
using AvaloniaDesigner.Generator.Utility;
using Microsoft.CodeAnalysis;

namespace AvaloniaDesigner.Generator.Builders
{
    public class FormClassBuilder
    {
        private readonly TypeResolver _resolver;
        private readonly ValueFormatter _formatter;
        private readonly SourceProductionContext _context;

        public FormClassBuilder(TypeResolver resolver, SourceProductionContext context)
        {
            _resolver = resolver;
            _context = context;
            _formatter = new ValueFormatter(resolver);
        }

        public string Build(AvaloniaModel model, string rootNamespace)
        {
            var sb = new StringBuilder();
            
            string ns = $"{rootNamespace}.{model.NamespaceSuffix}";

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using global::Avalonia.Controls;"); 
            sb.AppendLine("using global::System.Collections.Generic;");
            sb.AppendLine("using global::Avalonia.Media;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {model.FormName} : global::{model.ParentClassType}");
            sb.AppendLine("    {");

            var namedControls = CollectFields(model);
            _context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor("ADG9999", "DEBUG INFO", "Collected fields: {0}", "Debug", DiagnosticSeverity.Warning, true), 
                Location.None, string.Join(", ", namedControls.Select(c => c.Name + ":" + c.Type)) ));
            
            foreach (var control in namedControls.DistinctBy(c => c.Name))
            {
                sb.AppendLine($"        internal global::{control.Type} {control.Name};");
            }

            sb.AppendLine();
            sb.AppendLine("        public void InitializeComponent()");
            sb.AppendLine("        {");

            BuildMethodBody(sb, model);

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private void BuildMethodBody(StringBuilder sb, AvaloniaModel model)
        {
            var propertyGenerator = new PropertyGenerator(_resolver, _formatter, _context);
            var parentType = _resolver.ResolveType(model.ParentClassType);

            foreach (var prop in model.Properties)
            {
                propertyGenerator.GeneratePropertyAssignment(
                    sb, "this", parentType, prop.Key, prop.Value);
            }
        }

        private List<ControlInfo> CollectFields(AvaloniaModel model)
        {
            var controls = new List<ControlInfo>();
            var parentType = _resolver.ResolveType(model.ParentClassType);
            CollectFieldsFromProperties(model.Properties, parentType, controls);
            return controls;
        }
        
        private void CollectFieldsFromProperties(
            Dictionary<string, PropertyModel> properties, 
            INamedTypeSymbol? parentType, 
            List<ControlInfo> controls)
        {
            foreach (var propEntry in properties)
            {
                var prop = propEntry.Value;
                var propertyName = propEntry.Key;
                
                IPropertySymbol? targetPropSymbol = parentType != null 
                    ? _resolver.FindProperty(parentType, propertyName) 
                    : null;

                // 1. Обычное свойство, содержащее контрол (Content, Child, Background как объект и т.п.)
                if (!string.IsNullOrEmpty(prop.Type))
                {
                    string? controlName = FindControlName(prop);

                    if (!string.IsNullOrEmpty(controlName))
                    {
                        controls.Add(new ControlInfo 
                        { 
                            Type = prop.Type, 
                            Name = controlName 
                        });
                        _context.ReportDiagnostic(Diagnostic.Create(
                            new DiagnosticDescriptor("ADG9901", "Field Found", $"Found field: {controlName} ({prop.Type})", "Debug", DiagnosticSeverity.Warning, true), 
                            Location.None));
                    }
                    
                    var childType = _resolver.ResolveType(prop.Type);
                    CollectFieldsFromProperties(prop.Properties, childType, controls);
                }
                // 2. Свойство-коллекция (Children, Items и т.п.) — в новом формате всегда массив Items
                else if (targetPropSymbol != null && _resolver.IsCollectionType(targetPropSymbol.Type))
                {
                    _context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("ADG9902", "Collection Found", $"Processing collection: {propertyName} on type {parentType?.Name}", "Debug", DiagnosticSeverity.Warning, true), 
                        Location.None));

                    if (prop.Items == null || prop.Items.Count == 0)
                    {
                        _context.ReportDiagnostic(Diagnostic.Create(
                            new DiagnosticDescriptor("ADG9907", "Collection Empty Check", 
                            $"Collection {propertyName} on type {parentType?.Name} has no elements.", 
                            "Debug", DiagnosticSeverity.Warning, true), 
                            Location.None));
                        continue;
                    }
                    
                    foreach (var elementModel in prop.Items)
                    {
                        if (!string.IsNullOrEmpty(elementModel.Type))
                        {
                            string? controlName = FindControlName(elementModel);
                            
                            _context.ReportDiagnostic(Diagnostic.Create(
                                new DiagnosticDescriptor("ADG9904", "Find Name Check", $"Check for element in collection {propertyName}: FindControlName returned '{controlName}'", "Debug", DiagnosticSeverity.Warning, true), 
                                Location.None));
                                
                            if (!string.IsNullOrEmpty(controlName))
                            {
                                controls.Add(new ControlInfo 
                                { 
                                    Type = elementModel.Type, 
                                    Name = controlName 
                                });
                                _context.ReportDiagnostic(Diagnostic.Create(
                                    new DiagnosticDescriptor("ADG9903", "Collection Item Field Found", $"Found field in collection {propertyName}: {controlName} ({elementModel.Type})", "Debug", DiagnosticSeverity.Warning, true), 
                                    Location.None));
                            }
                            
                            var elementType = _resolver.ResolveType(elementModel.Type);
                            CollectFieldsFromProperties(elementModel.Properties, elementType, controls);
                        }
                    }
                }
            }
        }
        
        private string? FindControlName(PropertyModel model)
        {
            if (model.Properties.TryGetValue("Name", out PropertyModel? nameProp) && nameProp.Value != null)
            {
                if (nameProp.Value is string name)
                {
                    _context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor("ADG9905", "Name Found Value", $"Found Name='{name}' in properties.", "Debug", DiagnosticSeverity.Warning, true), 
                        Location.None));
                    return name;
                }
            }
            return null;
        }
    }
}
