using System;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using AvaloniaDesigner.Generator.Models; 

namespace AvaloniaDesigner.Generator
{
    [Generator(LanguageNames.CSharp)]
    public class FormGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.AdditionalTextsProvider
                .Where(f => Path.GetFileName(f.Path).EndsWith("Model.json", StringComparison.OrdinalIgnoreCase))
                .Collect();

            var compilationAndFiles = context.CompilationProvider.Combine(provider);

            context.RegisterSourceOutput(compilationAndFiles, GenerateCode);
        }

        private void GenerateCode(SourceProductionContext context, (Compilation Compilation, ImmutableArray<AdditionalText> Files) tuple)
        {
            var compilation = tuple.Compilation;
            var files = tuple.Files;
            
            // Получаем RootNamespace из сборки
            string rootNamespace = compilation.AssemblyName ?? "DefaultApp";

            foreach (var file in files)
            {
                string? jsonContent = file.GetText(context.CancellationToken)?.ToString();
                if (string.IsNullOrEmpty(jsonContent)) continue;

                try
                {
                    var formModel = JsonSerializer.Deserialize<FormModel>(jsonContent!, 
                        new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                    if (formModel == null) continue;

                    string sourceCode = GenerateFormClass(formModel, rootNamespace);
                    
                    context.AddSource($"{formModel.FormName}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
                }
                catch (JsonException ex)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "ADG0001", "Form Model Parsing Error",
                            $"Failed to parse JSON for {Path.GetFileName(file.Path)}: {ex.Message}",
                            "Generation", DiagnosticSeverity.Error, true),
                        Location.None));
                }
            }
        }

        private static string GenerateFormClass(FormModel model, string rootNamespace)
        {
            string ns = $"{rootNamespace}.{model.NamespaceSuffix}"; 
            var sb = new StringBuilder();

            // 1. Using директивы
            sb.AppendLine($"// <auto-generated/>");
            sb.AppendLine($"using Avalonia.Controls;");
            sb.AppendLine($"using Avalonia.Layout;");
            sb.AppendLine($"using Avalonia.Media;");
            sb.AppendLine($"using Avalonia.Data;");
            sb.AppendLine($"using System.Collections.Generic;"); 
            sb.AppendLine($"");
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            
            // 2. Объявление partial class
            sb.AppendLine($"    [global::System.CodeDom.Compiler.GeneratedCode(\"AvaloniaDesigner.Generator\", \"1.0.0.0\")]");
            sb.AppendLine($"    public partial class {model.FormName}"); 
            sb.AppendLine("    {");
            
            // 3. Поля (internal, без '_')
            foreach (var control in model.Controls)
            {
                sb.AppendLine($"        internal global::{control.Type} {control.Name};");
            }
            sb.AppendLine("        ");
            
            // 4. Метод InitializeComponent()
            sb.AppendLine("        public void InitializeComponent()"); 
            sb.AppendLine("        {");

            // Корневой контейнер
            string rootContainerType = model.RootContainer.Type;
            sb.AppendLine($"            global::{rootContainerType} root = new global::{rootContainerType}();");
            
            // Свойства корня
            foreach (var prop in model.RootContainer.Properties)
            {
                if (prop.Key == "ColumnDefinitions" && prop.Value.ValueKind == JsonValueKind.String)
                {
                    string colDefsString = prop.Value.GetString()!.Replace("\"", "\\\"");
                    sb.AppendLine($"            root.{prop.Key} = ColumnDefinitions.Parse(\"{colDefsString}\");");
                }
                else
                {
                    sb.AppendLine($"            root.{prop.Key} = {FormatValue(prop.Value, prop.Key)};");
                }
            }
            
            // RowDefinitions
            if (model.RootContainer.RowDefinitions != null && model.RootContainer.Type.EndsWith(".Grid"))
            {
                 foreach (var rowDef in model.RootContainer.RowDefinitions)
                 {
                     sb.AppendLine($"            root.RowDefinitions.Add(new RowDefinition(GridLength.Parse(\"{rowDef}\")));");
                 }
            }
            
            // Контролы
            foreach (var control in model.Controls)
            {
                sb.AppendLine($"            this.{control.Name} = new global::{control.Type}();");
                sb.AppendLine($"            this.{control.Name}.Name = \"{control.Name}\";");
                
                foreach (var prop in control.Properties)
                {
                    string propertyName = prop.Key;
                    
                    if (prop.Key.Contains(".")) 
                    {
                        string className = prop.Key.Split('.')[0];
                        propertyName = prop.Key.Split('.')[1];
                        sb.AppendLine($"            {className}.Set{propertyName}(this.{control.Name}, {FormatValue(prop.Value, propertyName)});");
                    }
                    else
                    {
                        sb.AppendLine($"            this.{control.Name}.{prop.Key} = {FormatValue(prop.Value, propertyName)};");
                    }
                }
                sb.AppendLine($"            root.Children.Add(this.{control.Name});");
            }

            sb.AppendLine($"            this.Content = root;");
            sb.AppendLine("        }");
            
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // --- Вспомогательные методы (без изменений) ---
        
        private static string GetCSharpEnum(string propertyName, string jsonValue)
        {
            string enumTypeName = "";
            
            // !!! ИСПРАВЛЕНО: ТОЧНОЕ СООТВЕТСТВИЕ ИМЕНИ СВОЙСТВА !!!
            if (propertyName.Equals("VerticalAlignment", StringComparison.OrdinalIgnoreCase))
                enumTypeName = "Avalonia.Layout.VerticalAlignment";
            else if (propertyName.Equals("HorizontalAlignment", StringComparison.OrdinalIgnoreCase))
                enumTypeName = "Avalonia.Layout.HorizontalAlignment"; 
            
            // Старая логика, которая была менее точной:
            // if (propertyName.Contains("HorizontalAlignment") || propertyName.Contains("VerticalAlignment"))
            //    enumTypeName = "Avalonia.Layout.HorizontalAlignment"; // <-- Здесь была ошибка

            else if (propertyName.Contains("Stretch"))
                enumTypeName = "Avalonia.Media.Stretch";
            else if (propertyName.Contains("Alignment") && !propertyName.Contains("Vertical") && !propertyName.Contains("Horizontal")) 
                enumTypeName = "Avalonia.Media.TextAlignment";
            
            if (string.IsNullOrEmpty(enumTypeName))
                return $"\"{jsonValue}\"";

            return $"{enumTypeName}.{jsonValue}";
        }

        private static string FormatValue(JsonElement element, string? propertyName = null)
        {
            if (element.ValueKind == JsonValueKind.String)
            {
                string value = element.GetString()!;
                
                if (propertyName != null && (propertyName.EndsWith("Brush") || propertyName.EndsWith("Background") || propertyName.EndsWith("Foreground") || propertyName.EndsWith("Color")))
                {
                    return $"new Avalonia.Media.SolidColorBrush(Avalonia.Media.Color.Parse(\"{value.Replace("\"", "\\\"")}\"))";
                }
                
                if (propertyName != null && (propertyName.EndsWith("Alignment") || propertyName.EndsWith("Stretch")))
                {
                    return GetCSharpEnum(propertyName, value);
                }

                return $"\"{value.Replace("\"", "\\\"")}\"";
            }
            
            return element.ValueKind switch
            {
                JsonValueKind.Number => element.GetRawText(),
                JsonValueKind.True => "true",
                JsonValueKind.False => "false",
                _ => $"\"{element.ToString()}\"" 
            };
        }
    }
}