using System;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using AvaloniaDesigner.Generator.Models;

namespace AvaloniaDesigner.Generator
{
    [Generator(LanguageNames.CSharp)]
    public class FormGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.AdditionalTextsProvider
                .Where(f => Path.GetFileName(f.Path)
                    .EndsWith("Model.json", StringComparison.OrdinalIgnoreCase))
                .Collect();

            var compilationAndFiles = context.CompilationProvider.Combine(provider);

            context.RegisterSourceOutput(compilationAndFiles, GenerateCode);
        }

        private void GenerateCode(
            SourceProductionContext context,
            (Compilation Compilation, ImmutableArray<AdditionalText> Files) tuple)
        {
            var compilation = tuple.Compilation;
            var files = tuple.Files;

            string rootNamespace = compilation.AssemblyName ?? "DefaultApp";

            foreach (var file in files)
            {
                string? jsonContent = file.GetText(context.CancellationToken)?.ToString();
                if (string.IsNullOrEmpty(jsonContent))
                    continue;

                try
                {
                    var formModel = JsonSerializer.Deserialize<FormModel>(
                        jsonContent!,
                        new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                    if (formModel is null)
                        continue;

                    string sourceCode = GenerateFormClass(formModel, rootNamespace, compilation);

                    context.AddSource(
                        $"{formModel.FormName}.g.cs",
                        SourceText.From(sourceCode, Encoding.UTF8));
                }
                catch (JsonException ex)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            id: "ADG0001",
                            title: "Form Model Parsing Error",
                            messageFormat: $"Failed to parse JSON for {Path.GetFileName(file.Path)}: {ex.Message}",
                            category: "Generation",
                            defaultSeverity: DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        Location.None));
                }
            }
        }

        private static string GenerateFormClass(
            FormModel model,
            string rootNamespace,
            Compilation compilation)
        {
            string ns = $"{rootNamespace}.{model.NamespaceSuffix}";
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Avalonia.Controls;");
            sb.AppendLine("using Avalonia.Layout;");
            sb.AppendLine("using Avalonia.Media;");
            sb.AppendLine("using Avalonia.Data;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"AvaloniaDesigner.Generator\", \"1.0.0.0\")]");
            sb.AppendLine($"    public partial class {model.FormName}");
            sb.AppendLine("    {");

            // Поля контролов
            foreach (var control in model.Controls)
            {
                sb.AppendLine($"        internal global::{control.Type} {control.Name};");
            }

            sb.AppendLine();
            sb.AppendLine("        public void InitializeComponent()");
            sb.AppendLine("        {");

            // Корневой контейнер
            string rootContainerType = model.RootContainer.Type;
            sb.AppendLine($"            global::{rootContainerType} root = new global::{rootContainerType}();");

            var rootTypeSymbol = ResolveType(compilation, rootContainerType);

            // Свойства корня
            foreach (var prop in model.RootContainer.Properties)
            {
                IPropertySymbol? propSymbol = rootTypeSymbol is null
                    ? null
                    : FindProperty(rootTypeSymbol, prop.Key);

                string valueExpr = FormatValueSemantic(
                    prop.Value,
                    propSymbol?.Type,
                    compilation,
                    prop.Key);

                sb.AppendLine($"            root.{prop.Key} = {valueExpr};");
            }

            // RowDefinitions – отдельная специализированная обработка
            if (model.RootContainer.RowDefinitions is not null &&
                model.RootContainer.Type.EndsWith(".Grid", StringComparison.Ordinal))
            {
                foreach (var rowDef in model.RootContainer.RowDefinitions)
                {
                    string rowDefStr = EscapeString(rowDef);
                    sb.AppendLine(
                        "            root.RowDefinitions.Add(" +
                        $"new global::Avalonia.Controls.RowDefinition(" +
                        $"global::Avalonia.Controls.GridLength.Parse(\"{rowDefStr}\")));");
                }
            }

            // Контролы
            foreach (var control in model.Controls)
            {
                sb.AppendLine($"            this.{control.Name} = new global::{control.Type}();");
                sb.AppendLine($"            this.{control.Name}.Name = \"{control.Name}\";");

                var controlTypeSymbol = ResolveType(compilation, control.Type);

                foreach (var prop in control.Properties)
                {
                    string propertyKey = prop.Key;

                    // attached-свойства: "Полный.Тип.Свойство"
                    if (propertyKey.Contains("."))
                    {
                        int lastDot = propertyKey.LastIndexOf('.');
                        if (lastDot > 0 && lastDot < propertyKey.Length - 1)
                        {
                            string ownerTypeName = propertyKey.Substring(0, lastDot);   // Avalonia.Controls.Grid
                            string attachedName = propertyKey.Substring(lastDot + 1);   // Row / Column / Dock ...

                            var ownerType = ResolveType(compilation, ownerTypeName);
                            IMethodSymbol? setter = ownerType is null
                                ? null
                                : FindAttachedSetter(ownerType, attachedName);

                            if (ownerType is not null && setter is not null)
                            {
                                var valueType = setter.Parameters.Length == 2
                                    ? setter.Parameters[1].Type
                                    : null;

                                string valueExpr = FormatValueSemantic(
                                    prop.Value,
                                    valueType,
                                    compilation,
                                    attachedName);

                                string ownerDisplayName = ownerType.ToDisplayString(
                                    SymbolDisplayFormat.FullyQualifiedFormat);

                                sb.AppendLine(
                                    $"            {ownerDisplayName}.{setter.Name}(this.{control.Name}, {valueExpr});");
                            }
                            else
                            {
                                // Fallback: если тип не нашли или нет сеттера – грубый старый вариант
                                string legacyExpr = FormatValueLegacy(prop.Value, attachedName);
                                sb.AppendLine(
                                    $"            {ownerTypeName}.Set{attachedName}(this.{control.Name}, {legacyExpr});");
                            }
                        }
                    }
                    else
                    {
                        IPropertySymbol? propSymbol = controlTypeSymbol is null
                            ? null
                            : FindProperty(controlTypeSymbol, propertyKey);

                        string valueExpr = FormatValueSemantic(
                            prop.Value,
                            propSymbol?.Type,
                            compilation,
                            propertyKey);

                        sb.AppendLine($"            this.{control.Name}.{propertyKey} = {valueExpr};");
                    }
                }

                sb.AppendLine($"            root.Children.Add(this.{control.Name});");
            }

            sb.AppendLine("            this.Content = root;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        // ---------------- Roslyn helpers ----------------

        private static INamedTypeSymbol? ResolveType(Compilation compilation, string metadataName)
            => compilation.GetTypeByMetadataName(metadataName);

        private static IPropertySymbol? FindProperty(INamedTypeSymbol type, string propertyName)
        {
            for (var t = type; t is not null; t = t.BaseType)
            {
                foreach (var member in t.GetMembers(propertyName))
                {
                    if (member is IPropertySymbol p)
                        return p;
                }
            }

            return null;
        }

        private static IMethodSymbol? FindAttachedSetter(INamedTypeSymbol ownerType, string attachedName)
        {
            string methodName = "Set" + attachedName;

            foreach (var member in ownerType.GetMembers(methodName))
            {
                if (member is IMethodSymbol m &&
                    m.IsStatic &&
                    m.Parameters.Length == 2)
                {
                    return m;
                }
            }

            return null;
        }

        // ---------------- Value formatting ----------------

        private static string FormatValueSemantic(
            JsonElement element,
            ITypeSymbol? targetType,
            Compilation compilation,
            string? propertyNameForLegacy = null)
        {
            if (targetType is null)
            {
                // Если тип не нашли – максимально простой fallback
                return FormatValueLegacy(element, propertyNameForLegacy);
            }

            // string
            if (targetType.SpecialType == SpecialType.System_String)
            {
                if (element.ValueKind == JsonValueKind.String)
                    return $"\"{EscapeString(element.GetString() ?? string.Empty)}\"";

                return $"\"{EscapeString(element.ToString())}\"";
            }

            // bool
            if (targetType.SpecialType == SpecialType.System_Boolean)
            {
                return element.ValueKind switch
                {
                    JsonValueKind.True  => "true",
                    JsonValueKind.False => "false",
                    JsonValueKind.String =>
                        bool.TryParse(element.GetString(), out var b1) && b1 ? "true" : "false",
                    JsonValueKind.Number =>
                        int.TryParse(element.GetRawText(), out var i) && i != 0 ? "true" : "false",
                    _ => "false"
                };
            }

            // числа
            if (targetType.SpecialType is SpecialType.System_Int16
                or SpecialType.System_Int32
                or SpecialType.System_Int64
                or SpecialType.System_Single
                or SpecialType.System_Double
                or SpecialType.System_Decimal)
            {
                return element.GetRawText();
            }

            // enum
            if (targetType.TypeKind == TypeKind.Enum)
            {
                if (element.ValueKind == JsonValueKind.String)
                {
                    string memberName = element.GetString() ?? string.Empty;
                    string enumTypeName = targetType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat);
                    return $"{enumTypeName}.{memberName}";
                }

                return element.GetRawText();
            }

            // IBrush – отдельный спец-кейс (учитываем nullability)
            if (IsAvaloniaBrushType(targetType, compilation))
            {
                string text = element.ValueKind == JsonValueKind.String
                    ? (element.GetString() ?? string.Empty)
                    : element.ToString();

                return $"global::Avalonia.Media.Brush.Parse(\"{EscapeString(text)}\")";
            }

            // string + Parse(string) для остальных типов
            if (element.ValueKind == JsonValueKind.String)
            {
                string text = element.GetString() ?? string.Empty;

                // 1) Parse на самом типе
                var parseOnType = FindParseOnType(targetType);
                if (parseOnType is not null)
                {
                    string typeName = targetType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat);
                    return $"{typeName}.Parse(\"{EscapeString(text)}\")";
                }

                // 2) Parse на совместимом типе (например, IBrush <- Brush.Parse)
                var parseForAssignable = FindParseForAssignableType(
                    compilation, targetType, out var parserType);
                if (parseForAssignable is not null && parserType is not null)
                {
                    string parserTypeName = parserType.ToDisplayString(
                        SymbolDisplayFormat.FullyQualifiedFormat);
                    return $"{parserTypeName}.Parse(\"{EscapeString(text)}\")";
                }

                // если ничего не нашли – просто строка
                return $"\"{EscapeString(text)}\"";
            }

            // общий fallback
            return FormatValueLegacy(element, propertyNameForLegacy);
        }

        private static IMethodSymbol? FindParseOnType(ITypeSymbol targetType)
        {
            foreach (var member in targetType.GetMembers("Parse"))
            {
                if (member is IMethodSymbol m &&
                    m.IsStatic &&
                    m.Parameters.Length == 1 &&
                    m.Parameters[0].Type.SpecialType == SpecialType.System_String &&
                    SymbolEqualityComparer.Default.Equals(m.ReturnType, targetType))
                {
                    return m;
                }
            }

            return null;
        }

        /// <summary>
        /// Поиск "парсера" для интерфейсных/базовых типов,
        /// например: IBrush <- Brush.Parse(string).
        /// </summary>
        private static IMethodSymbol? FindParseForAssignableType(
            Compilation compilation,
            ITypeSymbol targetType,
            out INamedTypeSymbol? parserType)
        {
            parserType = null;

            // Avalonia.Media.IBrush → Avalonia.Media.Brush.Parse(string)
            var brushInterface = compilation.GetTypeByMetadataName("Avalonia.Media.IBrush");
            if (brushInterface is not null && IsAssignableFrom(brushInterface, targetType))
            {
                parserType = compilation.GetTypeByMetadataName("Avalonia.Media.Brush");
                if (parserType is not null)
                {
                    foreach (var member in parserType.GetMembers("Parse"))
                    {
                        if (member is IMethodSymbol m &&
                            m.IsStatic &&
                            m.Parameters.Length == 1 &&
                            m.Parameters[0].Type.SpecialType == SpecialType.System_String &&
                            IsAssignableFrom(brushInterface, m.ReturnType))
                        {
                            return m;
                        }
                    }
                }
            }

            return null;
        }

        /// <summary>
        /// Проверяет, что targetType является Avalonia.Media.IBrush или реализует его
        /// (с учётом nullable-аннотаций).
        /// </summary>
        private static bool IsAvaloniaBrushType(ITypeSymbol targetType, Compilation compilation)
        {
            var brushInterface = compilation.GetTypeByMetadataName("Avalonia.Media.IBrush");
            if (brushInterface is null)
                return false;

            // убираем nullable-аннотацию, если есть
            if (targetType is INamedTypeSymbol named &&
                named.NullableAnnotation != NullableAnnotation.None)
            {
                targetType = named.WithNullableAnnotation(NullableAnnotation.None);
            }

            return IsAssignableFrom(brushInterface, targetType);
        }

        private static bool IsAssignableFrom(ITypeSymbol target, ITypeSymbol source)
        {
            if (SymbolEqualityComparer.Default.Equals(target, source))
                return true;

            foreach (var iface in source.AllInterfaces)
            {
                if (SymbolEqualityComparer.Default.Equals(target, iface))
                    return true;
            }

            var baseType = source.BaseType;
            while (baseType is not null)
            {
                if (SymbolEqualityComparer.Default.Equals(target, baseType))
                    return true;

                baseType = baseType.BaseType;
            }

            return false;
        }

        private static string FormatValueLegacy(JsonElement element, string? propertyName = null)
        {
            if (element.ValueKind == JsonValueKind.String)
            {
                string value = element.GetString() ?? string.Empty;
                return $"\"{EscapeString(value)}\"";
            }

            return element.ValueKind switch
            {
                JsonValueKind.Number => element.GetRawText(),
                JsonValueKind.True => "true",
                JsonValueKind.False => "false",
                _ => $"\"{EscapeString(element.ToString())}\""
            };
        }

        private static string EscapeString(string value)
            => value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
    }
}
